apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quarkus-servicemonitor
  namespace: custom-autoscaler-test
  labels:
    k8s-app: http-kafka-mock
spec:
  selector:
    matchLabels:
      app: http-kafka-mock
  endpoints:
  - port: http-kafka
    interval: 5s
    path: /q/metrics
    scheme: http
  namespaceSelector:
    matchNames:
      - custom-autoscaler-test